account:
  # Your private key with Link balance (https://faucets.chain.link/ free testnet faucet)
  private_key: ""
network:
  # Node websocket (Quicknode best choice)
  rpc_url: "wss://"
  is_testnet: true
  chain_id: 11155111 # sepolia
contracts:
  sample_test:
    name: "Sample test contract"
    short_name: "sampletest"
    address: "0xCb1Ad0A9D12993CB614533Cd19e7f9f555F13816" # sepolia
    version: "0_1"
    gas_limit: 500000
    execution_limit: 5
chainlink:
  registry_version: "2_0"
  topup_amount: "700000000000000000" #0.5
  upkeep_controller_address: "0x09970ef6d0E46F71E568538fD88B44127739D892"
  token_address: "0x779877A7B0D9E8603169DdbD7836e478b4624789"
  min_controller_approve: "300000000000000000000"
node:
  # Log level from -1 (more logs) to 5 (fewer logs)
  log_level: -1